backend:
  name: github
  repo: macaodhj/realising-education
  branch: main
  base_url: https://realising-education-cms-proxy.realising-cms.workers.dev
  auth_endpoint: oauth/authorize

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
